name: Koffein
options:
  bundleIdPrefix: app.r7m4x9
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
targets:
  Koffein:
    type: application
    platform: macOS
    sources:
      - path: Koffein
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.r7m4x9.macos
        PRODUCT_NAME: Koffein
        MARKETING_VERSION: 1.1.0
        CURRENT_PROJECT_VERSION: 2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Koffein
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Johan Karlsson"
        CODE_SIGN_IDENTITY: "-"
    scheme:
      testTargets:
        - KoffeinTests
  KoffeinTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: KoffeinTests
    dependencies:
      - target: Koffein
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.r7m4x9.macos.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: "-"
